### PR TITLE
add option to replace set-mark w/ jump-char

### LINKED ISSUE #21: Advice feature. When run `set-mark-command`, open jump-char-forward.
I think this is a better idea, When I do `set-mark-command`, What I need often is
jump to line ending, next word, next-char, the most often used command is `C-f`
`C-b`, `C-e`. those on the fly work well when jump-char-mode is active!

It seem like we does not missing anythings, But, we could add more
jump to functionality, it cool!

here is some defadvice does this
```cl
(defadvice set-mark-command (after active-jump-char activate)
  (when (region-active-p)
    (call-interactively 'jump-char-forward)))
```

Thanks.

### PR DESCRIPTION
**Pull request by lewang**
- fixes #21

### CODE REVIEW

**Comment by lewang** [comment]
@zw963 can you check if this fulfills your usecase?

Instead of C-@, you can just use jump-char.

**Comment by zw963** [comment]
>> I'm quite unclear what's being demonstrated. Can you discuss this in the actual PR? #23

Sorry for confuse,  We discuss the problem here.
The key is this PR questionable, But i could not find out this bug before.

With this PR, When i start emacs -Q with following config

(require 'jump-char)
(setq jump-char-set-mark t)
(global-set-key [(control ?\;)] 'jump-char-forward)
(add-hook 'isearch-mode-hook
          '(lambda ()
             (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
             ))

When I press: `C-; M-f`, `M-f` keybinding use `isearch-yank-word`, this is not correct.
In this case, we hope M-f invoke `forward-word` as `set-mark-command` does.

I think this expected behavior should be implement in #22.  it not worked as expected
too, because in my previous test, I does not add `isearch-mode-hook` to rebinding
key, so I don't test this behavior out. sorry.

I add a new reply to #22, please read that for more details.

**Comment by lewang** [comment]
Don't modify keymaps in hooks.  Try this from emacs -Q:

(require 'jump-char)
(global-set-key [(control ?\;)] 'jump-char-forward)
(define-key isearch-mode-map [(meta f)] 'isearch-yank-word)


On Wed, May 4, 2016 at 12:27 AM, Billy <notifications@github.com> wrote:

> I'm quite unclear what's being demonstrated. Can you discuss this in the
> actual PR? #23 <https://github.com/lewang/jump-char/pull/23>
>
> Sorry for confuse, We discuss the problem here.
> The key is this PR questionable, But i could not find out this bug before.
>
> With this PR, When i start emacs -Q with following config
>
> (require 'jump-char)
> (setq jump-char-set-mark t)
> (global-set-key [(control ?\;)] 'jump-char-forward)
> (add-hook 'isearch-mode-hook
> '(lambda ()
> (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
> ))
>
> When I press: C-; M-f, M-f keybinding use isearch-yank-word, this is not
> correct.
> In this case, we hope M-f invoke forward-word as set-mark-command does.
>
> I think this expected behavior should be implement in #22
> <https://github.com/lewang/jump-char/pull/22>. it not worked as expected
> too, because in my previous test, I does not add isearch-mode-hook to
> rebinding
> key, so I don't test this behavior out. sorry.
>
> I add a new reply to #22 <https://github.com/lewang/jump-char/pull/22>,
> please read that for more details.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/pull/23#issuecomment-216738375>
>



-- 
Le

**Comment by zw963** [comment]
> Don't modify keymaps in hooks.

It worked !  thx.  though this hack some what strange enough.
Most of my minor keybinding is defined in `???-mode-hook`.
those keybinding is work well until now.

**Comment by zw963** [comment]
Maybe we can define a new key map, e.g.  like #24,  `jump-char-base-map` or `jump-char-mode-map`.
this map should not inherit key binding from `isearch-mode-map`.  what about you think?

**Comment by lewang** [comment]
> what about you think?

No, don't set keys in mode hooks.  It's not supported.  I can think of no situation where this should be necessary.  You'll subtly break many things like what happened here.

If you're trying to delay initialization until package loads, use `eval-after-load`.

**Comment by lewang** [comment]
Do `jump-char-forward-set-mark` and `jump-char-backward-set-mark` help with
your usecase?  i.e. using these instead of "C-@"?

On Thu, May 5, 2016 at 3:40 AM, Billy <notifications@github.com> wrote:

> Maybe we can define a new key map, e.g. like #24
> <https://github.com/lewang/jump-char/pull/24>, jump-char-base-map or
> jump-char-mode-map.
> this map should not inherit key binding from isearch-mode-map. what about
> you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/pull/23#issuecomment-217094598>
>



-- 
Le

**Comment by zw963** [comment]
> Do `jump-char-forward-set-mark` and `jump-char-backward-set-mark` help with your usecase? i.e. using these instead of "C-@"?

Yes, it worked. 
Except: I could not rebinding isearch-mode-map in isearch-mode-hook. 
It is not a big deal, just werid for me.

**Comment by zw963** [comment]
Hi, there still some things to consider.

One good emacs hotkey is `C-u C-@`, which jump to the previous mark position.
we can run `C-u C-@ C-@ C-@ ...` continuously, which can skip to editing position
back.

When i do `(global-set-key [remap set-mark-command] 'jump-char-forward-set-mark)`,
this function is not worked again.

**Comment by lewang** [comment]
I don't plan on doing anything more on this issue.  In fact, if the two
commands added don't suit your usecase, I'm inclined to remove them
completely.

The only think I can add is your usecase is predicated on an unwillingness
to adopt the "Emacs" way.  I'm not going to implement more and more
complicated your approach.


On Sat, May 7, 2016 at 7:48 AM, Billy <notifications@github.com> wrote:

> Hi, there still some things to consider.
>
> One good emacs hotkey is C-u C-@, which jump to the previous mark
> position.
> we can run C-u C-@ C-@ C-@ ... continuously, which can skip to editing
> position
> back.
>
> When i do (global-set-key [remap set-mark-command]
> 'jump-char-forward-set-mark),
> this function is not worked again.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/pull/23#issuecomment-217631067>
>



-- 
Le

**Comment by lewang** [comment]
that is "more and more complicated logic" to suit your approach.

On Mon, May 9, 2016 at 12:25 PM, Le Wang <l26wang@gmail.com> wrote:

> I don't plan on doing anything more on this issue.  In fact, if the two
> commands added don't suit your usecase, I'm inclined to remove them
> completely.
>
> The only think I can add is your usecase is predicated on an unwillingness
> to adopt the "Emacs" way.  I'm not going to implement more and more
> complicated your approach.
>
>
> On Sat, May 7, 2016 at 7:48 AM, Billy <notifications@github.com> wrote:
>
>> Hi, there still some things to consider.
>>
>> One good emacs hotkey is C-u C-@, which jump to the previous mark
>> position.
>> we can run C-u C-@ C-@ C-@ ... continuously, which can skip to editing
>> position
>> back.
>>
>> When i do (global-set-key [remap set-mark-command]
>> 'jump-char-forward-set-mark),
>> this function is not worked again.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lewang/jump-char/pull/23#issuecomment-217631067>
>>
>
>
>
> --
> Le
>



-- 
Le

**Comment by zw963** [comment]
OK, fine. 

Thank you very much anyway.

this problem I think i could resolved myself. : )

**Comment by zw963** [comment]
Hi,  after some try, I could not make `jump-char-forward-set-mark` work fine
with C-u prefix. the only workaround is the early defadvice hack.

```cl
(require 'jump-char)
(global-set-key [(control ?\;)] 'jump-char-forward)
(global-set-key [(control meta ?\;)] 'jump-char-backward)
(defadvice set-mark-command (after active-jump-char activate)
  (when (region-active-p)
    (call-interactively 'jump-char-forward)))
```
With those settings, i could work very well with `C-@` or `C-u C-@ C-@`.
Though, i am not use `jump-char-forward-set-mark` anymore.

I am so sorry for report this ...
But, I still advise keep current behavior no changed, to avoid broken somethings ...

**Comment by zw963** [comment]
Hi, @lewang ,  sorry for distrub, there still another issues relative to this PR for report.

When i run `jump-char-forward-set-mark` (C-;), i have to press C-g (keyboard-quit) 
two times to deactive the highlight mark.

e.g.  `C-; C-g`, we could see the mark is still settings, when i moving char,
we could see the highlighted region active. 

I think it should be cancelled in this case. (Press C-g one time)
Current, i have to `C-; C-g C-g` to cancel this mark. 

Thanks.

**Comment by lewang** [comment]
So using your defadvice solution, none of these problems exist?

On Tue, May 10, 2016 at 11:46 AM, Billy <notifications@github.com> wrote:

> Hi, @lewang <https://github.com/lewang> , sorry for distrub, there still
> another issues relative to this PR for report.
>
> When i run jump-char-forward-set-mark (C-;), i have to press C-g
> (keyboard-quit)
> two times to deactive the highlight mark.
>
> e.g. C-; C-g, we could see the mark is still settings, when i moving char,
> we could see the highlighted region active.
>
> I think it should be cancelled in this case. (Press C-g one time)
> Current, i have to C-; C-g C-g to cancel this mark.
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewang/jump-char/pull/23#issuecomment-218200976>
>



-- 
Le

**Comment by zw963** [comment]
> So using your defadvice solution, none of these problems exist?

Problem is exist too.  :)
I think the two case is caused by same issue, so create this one.

**Comment by zw963** [comment]
This problem is only happen when press `C-g` (keyboard-escape).

In most case, when I press `C-@`, i want to do some operation.
e.g. `M-w` to cope content, `C-k` to kill,  in those case, work well
for me. I don't know why `C-g` could not cancel set-mark.
because default `set-mark-command` always could be cancelled
use this comand.

**Comment by zw963** [comment]
@lewang , still any plan to fixed this in the future ?

**Pull request merged**
