### PR TITLE
create keymap dynaimcally

### PR DESCRIPTION
**Pull request by lewang**
- This removes ordering problem where user customized iserach-mode-map
  after loading jump-char.

### CODE REVIEW

**Comment by joostkremers** [comment]
This commit seems to be causing a problem in my configuration. I'm using `use-package` to load `jump-char` in the following manner:

```
(use-package jump-char
  :ensure t
  :bind (("C-M-z" . jump-char-forward)
         ("M-z" . jump-char-backward)
         :map jump-char-isearch-map
         ("<return>" . jump-char-exit)))
```

This should bind `<return>` to `jump-char-exit` as soon as `jump-char` is loaded, and it has worked fine until now. Since this commit, however, when I try to use `jump-char`, I get the following error:

    lookup-key: Symbol’s value as variable is void: jump-char-isearch-map

What's the recommended way now to bind keys in `jump-char-isearch-map`?

**Comment by lewang** [comment]
In https://github.com/lewang/jump-char/pull/24 you can customize `jump-char-base-map`, does that work for you?

**Comment by joostkremers** [comment]
Yes, that works.

**Comment by lewang** [comment]
Ok #24 merged in master now.

**Comment by joostkremers** [comment]
Great, thanks!

**Comment by zw963** [comment]
Hi, this reply is relation to #23 lastest reply, please read that first.

>> Start from emacs -Q and show what actually happens vs what you expect to happen. 
I found this PR is not worked as I expected use emacs -Q with following config:

```cl
(require 'jump-char)
(global-set-key [(control ?\;)] 'jump-char-forward)
(add-hook 'isearch-mode-hook
          '(lambda ()
             (define-key isearch-mode-map [(meta f)] 'isearch-yank-word)
             ))
```

In this config, I define a new key in isearch-mode-hook for isearch interactive use.
But, this keymap is take effect in jump-char. 

When i press: `C-; M-f`, those `M-f` I hope run command `forward-word` just as
`C-@` should to do, but in this case, `M-f` run command `isearch-yank-word`.

Hope to explain clear enough. Thanks.

**Pull request merged**
